/*
 * OpenScope .out (ELF) parsing regression test.
 *
 * Verifies that .out files (same ELF format) parse global variables and
 * expand structure members via DWARF, with symtab fallback for variables
 * without debug info. Uses tests/elf_sample.out generated by
 * tests/gen_elf_out.py.
 */
#include <stdio.h>
#include <string.h>
#include <windows.h>

#include "app.h"
#include "elf.h"
#include "vartree.h"

OS_App g_app;

static int g_fails;

#define CHECK(c, what) do { \
    printf("%s %s\n", (c) ? "PASS" : "FAIL", what); \
    if (!(c)) g_fails++; \
} while (0)

static const OS_Leaf* leaf_by_name(const char* name)
{
    int i;
    for (i = 0; i < g_app.leaf_count; i++) {
        if (strcmp(g_app.leaves[i].name, name) == 0) return &g_app.leaves[i];
    }
    return NULL;
}

int main(void)
{
    char err[256] = "";
    OS_ElfFile* elf;
    int idx;

    setvbuf(stdout, NULL, _IONBF, 0);
    memset(&g_app, 0, sizeof(g_app));

    /* non-ELF file with .out extension must be rejected by magic */
    {
        FILE* f = fopen("tests/not_elf.out", "wb");
        if (f) {
            fputs("this is not an elf file", f);
            fclose(f);
        }
    }
    CHECK(os_elf_open("tests/not_elf.out", err, sizeof(err)) == NULL,
          ".out non-ELF rejected by magic check");
    CHECK(strstr(err, "not an ELF") != NULL, "error message says not an ELF");

    elf = os_elf_open("tests/elf_sample.out", err, sizeof(err));
    CHECK(elf != NULL, "os_elf_open loads .out (ELF)");
    if (!elf) {
        printf("  err: %s\n", err);
        return 1;
    }
    CHECK(os_elf_machine(elf) == 40, "machine is EM_ARM");
    CHECK(os_elf_bits(elf) == 32, "ELF32");


    /* g_counter: int @0x20000000 from DWARF + symtab */
    idx = os_elf_find_var(elf, "g_counter");
    CHECK(idx >= 0, "g_counter present");
    if (idx >= 0) {
        const OS_Variable* v = os_elf_var_at(elf, idx);
        CHECK(v->address == 0x20000000u, "g_counter address 0x20000000");
        CHECK(v->has_debug == 1, "g_counter has debug type");
        CHECK(v->type && v->type->kind == OS_TYPE_INT, "g_counter type int");
        CHECK(v->type && v->type->size == 4, "g_counter size 4");
    }

    /* g_cfg: struct cfg_t { int a; int b; } @0x20000010 */
    idx = os_elf_find_var(elf, "g_cfg");
    CHECK(idx >= 0, "g_cfg present");
    if (idx >= 0) {
        const OS_Variable* v = os_elf_var_at(elf, idx);
        CHECK(v->address == 0x20000010u, "g_cfg address 0x20000010");
        CHECK(v->type && v->type->kind == OS_TYPE_STRUCT, "g_cfg type struct");
        CHECK(v->type && v->type->size == 8, "g_cfg size 8");
        if (v->type) {
            CHECK(v->type->child_count == 2, "struct has 2 members");
            if (v->type->child_count >= 2) {
                OS_Type* a = v->type->children[0];
                OS_Type* b = v->type->children[1];
                CHECK(a && a->name && strcmp(a->name, "a") == 0, "member a named a");
                CHECK(a && a->member_offset == 0, "member a offset 0");
                CHECK(b && b->name && strcmp(b->name, "b") == 0, "member b named b");
                CHECK(b && b->member_offset == 4, "member b offset 4");
            }
        }
    }

    /* g_raw: symtab only, no DWARF type */
    idx = os_elf_find_var(elf, "g_raw");
    CHECK(idx >= 0, "g_raw from symtab fallback");
    if (idx >= 0) {
        const OS_Variable* v = os_elf_var_at(elf, idx);
        CHECK(v->address == 0x20000020u, "g_raw address 0x20000020");
        CHECK(v->has_debug == 0, "g_raw has no debug type");
        CHECK(v->symbol_size == 4, "g_raw symbol size 4");
    }

    /* struct expansion through vartree leaves */
    g_app.elf = elf;
    os_vartree_build();
    CHECK(g_app.leaf_count >= 4, "vartree leaves >= 4");
    {
        const OS_Leaf* l;
        l = leaf_by_name("g_counter");
        CHECK(l && l->address == 0x20000000u && l->size == 4, "leaf g_counter");
        l = leaf_by_name("g_cfg.a");
        CHECK(l && l->address == 0x20000010u && l->size == 4, "leaf g_cfg.a @0x20000010");
        l = leaf_by_name("g_cfg.b");
        CHECK(l && l->address == 0x20000014u && l->size == 4, "leaf g_cfg.b @0x20000014");
        l = leaf_by_name("g_raw");
        CHECK(l && l->address == 0x20000020u, "leaf g_raw");
    }

    os_elf_close(elf);
    g_app.elf = NULL;

    printf(g_fails == 0 ? "ALL PASS\n" : "FAILURES: %d\n", g_fails);
    return g_fails == 0 ? 0 : 1;
}
